<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SaGH8nBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SaGH8nB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SaGH8nB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'espacioRepository' => ['privates', 'App\\Repository\\EspacioRepository', 'getEspacioRepositoryService', true],
        ], [
            'em' => '?',
            'espacioRepository' => 'App\\Repository\\EspacioRepository',
        ]);
    }
}
