<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pnhyk4iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pnhyk4i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pnhyk4i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etiquetaRepository' => ['privates', 'App\\Repository\\EtiquetaRepository', 'getEtiquetaRepositoryService', true],
        ], [
            'etiquetaRepository' => 'App\\Repository\\EtiquetaRepository',
        ]);
    }
}
