<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WDwtWMvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WDwtWMv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WDwtWMv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entrada' => ['privates', '.errored..service_locator.WDwtWMv.App\\Entity\\Entrada', NULL, 'Cannot autowire service ".service_locator.WDwtWMv": it references class "App\\Entity\\Entrada" but no such service exists.'],
        ], [
            'entrada' => 'App\\Entity\\Entrada',
        ]);
    }
}
