<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vg7VALQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Vg7VALQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Vg7VALQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entradaRepository' => ['privates', 'App\\Repository\\EntradaRepository', 'getEntradaRepositoryService', true],
        ], [
            'entradaRepository' => 'App\\Repository\\EntradaRepository',
        ]);
    }
}
