<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XVL_AyKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XVL.AyK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XVL.AyK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'espacioRepository' => ['privates', 'App\\Repository\\EspacioRepository', 'getEspacioRepositoryService', true],
        ], [
            'espacioRepository' => 'App\\Repository\\EspacioRepository',
        ]);
    }
}
