<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZZF4sK5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZZF4sK5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZZF4sK5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entrada' => ['privates', '.errored..service_locator.ZZF4sK5.App\\Entity\\Entrada', NULL, 'Cannot autowire service ".service_locator.ZZF4sK5": it references class "App\\Entity\\Entrada" but no such service exists.'],
            'entradaRepository' => ['privates', 'App\\Repository\\EntradaRepository', 'getEntradaRepositoryService', true],
        ], [
            'entrada' => 'App\\Entity\\Entrada',
            'entradaRepository' => 'App\\Repository\\EntradaRepository',
        ]);
    }
}
