<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BY0BjiDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BY0BjiD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BY0BjiD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entradaRepository' => ['privates', 'App\\Repository\\EntradaRepository', 'getEntradaRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'entradaRepository' => 'App\\Repository\\EntradaRepository',
            'paginator' => '?',
        ]);
    }
}
