<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HKphIDzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hKphIDz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hKphIDz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'espacio' => ['privates', '.errored..service_locator.hKphIDz.App\\Entity\\Espacio', NULL, 'Cannot autowire service ".service_locator.hKphIDz": it references class "App\\Entity\\Espacio" but no such service exists.'],
        ], [
            'espacio' => 'App\\Entity\\Espacio',
        ]);
    }
}
