<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nz_TNU0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nz.tNU0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nz.tNU0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etiquetum' => ['privates', '.errored..service_locator.Nz.tNU0.App\\Entity\\Etiqueta', NULL, 'Cannot autowire service ".service_locator.Nz.tNU0": it references class "App\\Entity\\Etiqueta" but no such service exists.'],
        ], [
            'etiquetum' => 'App\\Entity\\Etiqueta',
        ]);
    }
}
