<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2CiZGMvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2CiZGMv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2CiZGMv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usuario' => ['privates', '.errored..service_locator.2CiZGMv.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.2CiZGMv": it references class "App\\Entity\\Usuario" but no such service exists.'],
        ], [
            'usuario' => 'App\\Entity\\Usuario',
        ]);
    }
}
