<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FUqC5CDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fUqC5CD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fUqC5CD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'usuario' => ['privates', '.errored..service_locator.fUqC5CD.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.fUqC5CD": it references class "App\\Entity\\Usuario" but no such service exists.'],
            'usuarioRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'passwordHasher' => '?',
            'usuario' => 'App\\Entity\\Usuario',
            'usuarioRepository' => 'App\\Repository\\UsuarioRepository',
        ]);
    }
}
