<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FWd3jOcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FWd3jOc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FWd3jOc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entradaRepository' => ['privates', 'App\\Repository\\EntradaRepository', 'getEntradaRepositoryService', true],
            'usuarioRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'entradaRepository' => 'App\\Repository\\EntradaRepository',
            'usuarioRepository' => 'App\\Repository\\UsuarioRepository',
        ]);
    }
}
