<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEspacioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R0QYijb.App\Entity\Espacio' shared service.
     *
     * @return \App\Entity\Espacio
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R0QYijb": it references class "App\\Entity\\Espacio" but no such service exists.');
    }
}
