<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntradaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EntradaType' shared autowired service.
     *
     * @return \App\Form\EntradaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EntradaType.php';

        return $container->privates['App\\Form\\EntradaType'] = new \App\Form\EntradaType();
    }
}
