<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrada2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZZF4sK5.App\Entity\Entrada' shared service.
     *
     * @return \App\Entity\Entrada
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZZF4sK5": it references class "App\\Entity\\Entrada" but no such service exists.');
    }
}
