<?php

namespace ContainerXIHjSsT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEtiqueta2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.v6G2LRw.App\Entity\Etiqueta' shared service.
     *
     * @return \App\Entity\Etiqueta
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.v6G2LRw": it references class "App\\Entity\\Etiqueta" but no such service exists.');
    }
}
